version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - pdf

build:
  image: latest

python:
  version: 3.12
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - validation