# .readthedocs.yml
version: 2

# Build documentation with the following Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Python setup configuration
python:
  version: 3.12
  install:
    - requirements: requirements.txt

# The `build` section is used for controlling the documentation building process
build:
  image: latest

# Specify the location of the documentation
docs_dir: docs

# Optional: specify a custom branch to build
branches:
  - main